AWSTemplateFormatVersion: 2010-09-09

# custom resources uses only one resource creation this will be called and this will be triggered and other one lambda,
# we can use only one lambda that will be triggered. will use cfn resources
Resources:
  dynamodbtable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "cod_chav_patc"
          AttributeType: "S"
        - AttributeName: "cod_ordenar_chav"
          AttributeType: "S"
        - AttributeName: "status_ordenar"
          AttributeType: "S"
        - AttributeName: "tipo_ordenar"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "cod_chav_patc"
          KeyType: "HASH"
        - AttributeName: "cod_ordenar_chav"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "tbff2022_notification_centro"
      SSESpecification:
        SSEEnabled: true
      LocalSecondaryIndexes:
        - IndexName: "xxnc_2022"
          KeySchema:
            - AttributeName: "cod_chav_patc"
              KeyType: "HASH"
            - AttributeName: "status_ordenar"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "xxnc_2022_v1"
          KeySchema:
            - AttributeName: "cod_chav_patc"
              KeyType: "HASH"
            - AttributeName: "tipo_ordenar"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      Tags:
        - Key: "app"
          Value: "notificationcenter"