
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  dynamodbtable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "cod_chav_patc"
          AttributeType: "S"
        - AttributeName: "cod_ordenar_chav"
          AttributeType: "S"
        - AttributeName: "sigla_ordenar"
          AttributeType: "S"
        - AttributeName: "status_ordenar"
          AttributeType: "S"
        - AttributeName: "status_sigla_ordenar"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "cod_chav_patc"
          KeyType: "HASH"
        - AttributeName: "cod_ordenar_chav"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "tbff2022_notification_centro_test"
      SSEEnabled: True
      LocalSecondaryIndexes:
        - IndexName: "xxnc_2022"
          KeySchema:
            - AttributeName: "cod_chav_patc"
              KeyType: "HASH"
            - AttributeName: "sigla_ordenar"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "xxnc_2022_v1"
          KeySchema:
            - AttributeName: "cod_chav_patc"
              KeyType: "HASH"
            - AttributeName: "status_ordenar"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "xxnc_2022_v2"
          KeySchema:
            - AttributeName: "cod_chav_patc"
              KeyType: "HASH"
            - AttributeName: "status_sigla_ordenar"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      Tags:
        - Key: "app"
          Value: "notificationcenter"